# Skill Recommendations for Job Seekers {#job-search-coach}

#### Keywords {-}

job search, employment, education, skills gap

## Specialization creates a mismatch between jobs and qualified candidates

Despite low levels of overall unemployment, the US economy faces skills gap in many industries such as healthcare, IT, and manufacturing. This leads to both unfilled vacancies and workers without jobs. Moreover, according to the Third Way Center, "[m]ost of these occupations do not necessarily require four-year college degrees, but do require specialized training and some sort of credential" [@stephens_mind_2017]. This means that the skills gap could be bridged if job seekers could acquire these relatively low-cost credentials. Third Way estimates that there are 6 million unfilled "middle-skill" jobs, making this a huge opportunity for workers who can fill the gap. However, workers frequently consider education and employment as two related but separate problems, potentially missing out on training opportunities that could significantly advance their careers. 

As technology continues to advance, workers will need to seek retraining and change jobs more frequently [@economist_lifelong_2017]. Currently, it is not easy for workers to understand which new skills are most in-demand. This can lead to significant losses, as workers fail to obtain skills or, worse, spend time and money obtaining the wrong ones. The importance of identifying the best skills for each worker will only become greater over time. This project will endeavor to help fill the demand for skilled workers and to help job seekers advance their careers by providing them with customized recommendations for training and certification programs that would most benefit them.

## Returns to gaining specific skills can be predicted 

In-demand skills can be identified by observing current job listings. These skills can then be translated into specific training and certification courses that are recommended to job seekers. These recommendations would provide the job seeker with tangible options for gaining new skills, along with some estimate of their gains from doing so.

Given a database of job listings and their requirements, the skill gap for each type of skills or certification can be estimated. This would allow us to identify which skills are most likely to get job seekers' jobs. If we also have information on the wages of those jobs, we can estimate which skills earn workers the most money. More specifically, we can collect a dataset that counts the number of current job listings that require each type of skill or certification over time and the average wages of those listings. Then, we can forecast the expected number of job openings requiring each skill or certification, and how much they would pay. This would tell us what kind of opportunities a worker could expect if they were to start taking classes to acquire a certification today. These estimates would also be able to account for a job seeker's location in order to make them more relevant to that person. 

Specific certifications would need to be categorized into broader categories. For instance, certifications for hairdressers from different states would be categorized as (nearly) equivalent, and then might be grouped with certifications for estheticians into a 'beauty' category. Depending on the scale of the implementation, this could be done manually or by observing which certification names and other keywords appear together in job listings (or appear in similar job listings). Different skills could be grouped in a variety of ways (e.g. the most common industry they are used in, the most common job titles requiring them, the licensing organization they are given by), and these similarities could be exploited to provide more accurate estimates of demand for skills where data coverage might be poor. These categories could also be used to provide more high-level, long-range predictions about groups of skills, such as which might be displaced by technological change in the medium term.

Given a database of job seekers and their characteristics, ideally including education and job history, we can recommend skills that have the potential to give job seekers the largest return. These would be skills or certifications that would open up the most new jobs that the job seeker wasn't previously qualified for. These recommendations could then be matched with specific training and certification courses, each of which would require different investments of time and money for different returns. Ideally, we would also have some data on the actual outcomes from the courses we are recommending, to avoid sending workers to subpar (or outright fraudulent) providers. These expected returns can then be provided to job seekers, giving them a personalized experience and minimizing the amount of friction between them and a potentially beneficial education opportunity.

## Job seekers can better understand their choices with more information

By integrating the process of retraining and job seeking, workers are empowered to make better decisions about the path of their career. Job seekers can survey their full list of options for both jobs and retraining, hopefully encountering some options they had not even considered before. They can do this in a way that makes the benefits of retraining clear and tangible, reducing the inaction produced by lack of easily available information and the lure of the status quo. This tool could even be used by workers who are not currently looking for another job, but still want to be on the lookout for potential opportunities. 

From the perspective of the business providing these recommendations, this also presents an opportunity to provide extremely targeted advertising for organizations that run these training and certification courses. By connecting workers and education companies in this way, we can generate value for both sides, increase the efficiency of the job market, and help to close the skills gap.